apiVersion: apps/v1
kind: Deployment
metadata:
  name: onewatch
  namespace: tilt-integration
  labels:
    app: onewatch
spec:
  selector:
    matchLabels:
      app: onewatch
  template:
    metadata:
      labels:
        app: onewatch
    spec:
      containers:
      - name: onewatch
        image: gcr.io/windmill-test-containers/integration/onewatch
        ports:
        - containerPort: 8000
